export const TYPOGRAPHY = {
  Big_Display: {
    fontFamily: "pretendard",
    fontSize: "140px",
    fontWeight: 700,
    lineHeight: "140px",
    letterSpacing: "-0.5px",
  },
  Display: {
    fontFamily: "pretendard",
    fontSize: "32px",
    fontWeight: 700,
    lineHeight: "48px",
    letterSpacing: "-0.5px",
  },
  Big_Headline: {
    fontFamily: "pretendard",
    fontSize: "82px",
    fontWeight: 700,
    lineHeight: "72px",
    letterSpacing: "-0.5px",
  },
  Headline1: {
    fontFamily: "pretendard",
    fontSize: "24px",
    fontWeight: 700,
    lineHeight: "36px",
    letterSpacing: "-0.5px",
  },
  Headline2: {
    fontFamily: "pretendard",
    fontSize: "20px",
    fontWeight: 600,
    lineHeight: "32px",
    letterSpacing: "-0.25px",
  },
  Subtitle: {
    fontFamily: "pretendard",
    fontSize: "16px",
    fontWeight: 600,
    lineHeight: "28px",
    letterSpacing: "-0.25px",
  },
  Body1: {
    fontFamily: "pretendard",
    fontSize: "16px",
    fontWeight: 500,
    lineHeight: "24px",
    letterSpacing: "0.3px",
  },
  Body2: {
    fontFamily: "pretendard",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "22px",
    letterSpacing: "0.3px",
  },
  Body3: {
    fontFamily: "pretendard",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "20px",
    letterSpacing: "0.3px",
  },
  Caption: {
    fontFamily: "pretendard",
    fontSize: "12px",
    fontWeight: 400,
    lineHeight: "16px",
    letterSpacing: "0.3px",
  },
  point_text1: {
    fontFamily: "Bebas Neue",
    fontSize: "220px",
    fontWeight: 400,
    lineHeight: "auto",
    letterSpacing: "0.3px",
  },
  point_text2: {
    fontFamily: "Bebas Neue",
    fontSize: "200px",
    fontWeight: 400,
    lineHeight: "auto",
    letterSpacing: "0.3px",
  },
  point_text3: {
    fontFamily: "Bebas Neue",
    fontSize: "100px",
    fontWeight: 400,
    lineHeight: "auto",
    letterSpacing: "0.3px",
  },
  point_text4: {
    fontFamily: "Bebas Neue",
    fontSize: "24px",
    fontWeight: 400,
    lineHeight: "auto",
    letterSpacing: "0.3px",
  },
};
